uerp/urls.py
import autocomplete_light
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

from uerp.apps.ppc.views import PPCDayReport
from uerp.apps.hr.views import LoginView, LogoutView
from uerp.settings.common import MEDIA_ROOT, MEDIA_URL

autocomplete_light.autodiscover()
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', RedirectView.as_view(url='/ppc/')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    
    url(r'^ppc/$', PPCDayReport.as_view()),
    url(r'^hr/', include('uerp.apps.hr.urls', namespace='hr')),
)

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

uerp/apps/ppc/models.py
from django.db import models
from uerp.apps.res.models import User


class ProcessLaunch(models.Model):
    partner_id = models.IntegerField('Партнер')
    service_id = models.IntegerField('Услуга')
    process_model = models.CharField('Модель', max_length=64)

    def __str__(self):
        return self.process_model

    class Meta:
        db_table = 'process_launch'


class ProcessPPC(models.Model):
    launch = models.ForeignKey('ProcessLaunch', verbose_name='Карточка запуска')
    campaign = models.CharField('Кампания', max_length=200)
    site_url = models.CharField('Сайт', max_length=255)
    date_start = models.DateField('Дата запуска кампании')
    state = models.TextField('Статус')

    def __str__(self):
        return self.site_url

    class Meta:
        db_table = 'process_ppc'


class ProcessPPCFact(models.Model):
    ppc = models.ForeignKey('ProcessPPC', verbose_name='PPC')
    campaign = models.CharField('Кампания', max_length=100)
    cash = models.FloatField('Факт')
    date = models.DateField('Дата')

    def __str__(self):
        return self.campaign

    class Meta:
        db_table = 'report_day_ppc_statistic'


class ProcessPPCDayReport(models.Model):
    partner = models.ForeignKey('partner.Partner', verbose_name='Партнер')
    service_id = models.IntegerField('Услуга')
    specialist = models.ForeignKey('res.User', verbose_name='Аккаунт-менеджер')
    domain_zone = models.TextField('Доменная зона')
    campaign = models.CharField('Кампания', max_length=200)
    cash = models.FloatField('Факт')
    date = models.DateField('Дата')

    class Meta:
        db_table = 'report_day_ppc'

ppc/views.py
from django.shortcuts import render
from django.views.generic import ListView
import itertools
from ppc.models import ProcessPPCDayReport
from res.models import Employee


class PPCDayReport(ListView):
    model = ProcessPPCDayReport
    template_name = 'ppc/day_report.html'
    queryset = ProcessPPCDayReport.objects.all().order_by('partner_id', 'campaign', 'date')

    def get_context_data(self, **kwargs):
        context = super(PPCDayReport, self).get_context_data(**kwargs)
        dates = list(set([i.date for i in self.queryset]))
        dates.sort()
        context['dates'] = dates
        report = []
        for partner, i in itertools.groupby(self.queryset, lambda x: x.partner_id):

            for campaign, j in itertools.groupby(i, lambda x: x.campaign):
                record = {
                    'partner': partner,
                    'campaign': campaign,
                }
                record_dates = {}
                for item in j:
                    if not record.get('specialist'):
                        record['specialist'] = item.specialist_id
                    if not record.get('service'):
                        record['service'] = item.service_id
                    if not record.get('domain_zone'):
                        record['domain_zone'] = item.domain_zone
                    record_dates[item.date] = item.cash
                for date in dates:
                    if not record_dates.get(date):
                        record_dates[date] = '-'
                record['dates'] = sorted([{'date': d, 'cash': c} for d, c in record_dates.items()], key=lambda d: d['date'])
                report.append(record)
        context['report_list'] = report
        return context

uerp/apps/ppc/views.py
import itertools
from django.db.models import Q
from django.views.generic import ListView
from uerp.apps.ppc.models import ProcessPPCDayReport


class PPCDayReport(ListView):
    model = ProcessPPCDayReport
    template_name = 'ppc/day_report.html'

    def get_context_data(self, **kwargs):
        context = super(PPCDayReport, self).get_context_data(**kwargs)
        queryset = self.get_queryset()
        if queryset:
            dates = list(set([i.date for i in queryset if i.date is not None]))
            dates.sort()
            context['dates'] = dates
            report = []
            for partner, i in itertools.groupby(queryset, lambda x: x.partner):
                for campaign, j in itertools.groupby(i, lambda x: x.campaign):
                    record = {
                        'partner': partner,
                        'campaign': campaign,
                    }
                    record_dates = {}
                    for item in j:
                        if not record.get('specialist'):
                            record['specialist'] = item.specialist
                        if not record.get('service'):
                            record['service'] = item.service_id
                        if not record.get('domain_zone'):
                            record['domain_zone'] = item.domain_zone
                        record_dates[item.date] = item.cash or 0.0
                    for date in dates:
                        if not record_dates.get(date):
                            record_dates[date] = '-'
                    record['dates'] = sorted([{'date': d, 'cash': c} for d, c in record_dates.items()], key=lambda d: d['date'])
                    report.append(record)
            context['report_list'] = report
            context['search'] = {
                'campaign': self.request.REQUEST.get("campaign", ''),
                'partner': self.request.REQUEST.get("partner", ''),
                'date_start': self.request.REQUEST.get("date_start", ''),
                'date_end': self.request.REQUEST.get("date_end", ''),
                'specialist': self.request.REQUEST.get("specialist", ''),
            }
        return context

    def get_queryset(self):
        campaign = self.request.REQUEST.get("campaign")
        partner = self.request.REQUEST.get("partner")
        date_start = self.request.REQUEST.get("date_start")
        date_end = self.request.REQUEST.get("date_end")
        specialist = self.request.REQUEST.get("specialist")
        query = []
        if campaign:
            query.append(Q(campaign=campaign))
        if partner:
            query.append(Q(partner__name__icontains=partner) | Q(partner__ur_name__icontains=partner))
        if date_start:
            query.append(Q(date__gte=date_start))
        if date_end:
            query.append(Q(date__lte=date_end))
        if specialist:
            query.append(Q(specialist__name__icontains=specialist))

        if query:
            queryset = ProcessPPCDayReport.objects.prefetch_related('partner', 'specialist').filter(*query).order_by('partner', 'campaign', 'date')
            return queryset
        return ProcessPPCDayReport.objects.prefetch_related('partner', 'specialist').order_by('partner', 'campaign', 'date')

uerp/apps/ppc/templates/ppc/day_report.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_css %}
    {% include 'autocomplete_light/static.html' %}
{% endblock %}

{% block search %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="get" class="form-inline" role="form">
                <div class="form-group">
                    <label for="id_campaign">Кампания</label>
                    <input id="id_campaign" name="campaign" type="text" class="form-control" placeholder="Введите ID кампании" value="{{ search.campaign }}">
                </div>
                <div class="form-group">
                    <label for="id_partner">Партнер</label>
                    <input id="id_partner" name="partner" type="text" class="form-control" placeholder="Введите партнера" value="{{ search.partner }}">
                </div>
                <div class="form-group ">
                    <label for="id_specialist">Аккаунт-менеджер</label>
                    <input id="id_specialist" name="specialist" type="text" class="form-control" placeholder="Введите имя аккаунт-менеджера" value="{{ search.specialist }}">
                </div>
                <div class="form-group ">
                    <label for="id_date_start">Даты</label>
                    <input id="id_date_start" name="date_start" type="date" class="form-control" placeholder="Введите дату начала периода" value="{{ search.date_start }}">
                </div>
                <div class="form-group ">
                    <label for="id_date_end"></label>
                    <input id="id_date_end" name="date_end" type="date" class="form-control" placeholder="Введите дату конца периода" value="{{ search.date_end }}">
                </div>

                <br />
                <p>
                    <input type="submit" value="Поиск" class="btn btn-success">
                </p>
            </form>
        </div>
    </div>
{% endblock %}

{% block page %}
<table class="table table-hover table-condensed">
    <thead>
    <tr>
        <td>Партнер</td>
        <td>Кампания</td>
        <td>Аккаунт-менеджер</td>
        <td>Услуга</td>
        <td>Доменная зона</td>
        {% for date in dates %}
        <td>{{ date }}</td>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for item in report_list %}
    <tr>
        <td class="success">{{ item.partner }}</td>
        <td>{{ item.campaign }}</td>
        <td>{{ item.specialist }}</td>
        <td>{{ item.service }}</td>
        <td>{{ item.domain_zone }}</td>
        {% for date in item.dates %}
            <td>
                {{ date.cash }}
            </td>
        {% endfor %}

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}